parameters:
    locale: 'fr'
    images_directory: '%kernel.project_dir%/public/images/'
    trick_limit: 8
    comment_limit: 12
    user_limit: 3
    comment_user_limit: 3
    trick_user_limit: 3

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Twig\Extra\Intl\IntlExtension:
        tags: [ 'twig.extension' ]

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Doctrine\Migrations\Version\DbalMigrationFactory: ~
    App\Migrations\Factory\MigrationFactoryDecorator:
        decorates: Doctrine\Migrations\Version\DbalMigrationFactory
        arguments: ['@App\Migrations\Factory\MigrationFactoryDecorator.inner', '@service_container']
